version: "3"

services:

    app:
        build:
            args:
                user: laravel 
                uid: 1000
            context: ./src
            dockerfile: ../Dockerfile
        image: laraveldocker
        container_name: laraveldocker-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        networks:
            - laraveldocker
    
    db:
        image: mysql:5.7
        container_name: laraveldocker-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - laraveldocker

    nginx:
        image: nginx:1.17-alpine
        container_name: laraveldocker-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - laraveldocker

    nodejs:
        image: node:12-alpine
        container_name: laraveldocker-nodejs
        ports:
            - 3000:3000
        volumes:
            - ./src:/var/www
        networks:
            - laraveldocker

networks:
    laraveldocker:
        driver: bridge
